apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: votexxxxxx
    tier: front
  name: vote11
spec:
  ports:
  - name: "80"
    nodePort: 30000
    protocol: TCP
    targetPort: 80
  selector:
    app: vote
  type: NodePort
status:
  loadBalancer: {}
